<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bCHlcTr' shared service.

return $this->privates['.service_locator.bCHlcTr'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('livro' => function (): \App\Entity\Livro {
    return ($this->privates['.errored..service_locator.bCHlcTr.App\Entity\Livro'] ?? $this->load('getLivroService.php'));
}));
