<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZbMpHNx\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZbMpHNx/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZbMpHNx.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerZbMpHNx\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerZbMpHNx\srcProdProjectContainer(array(
    'container.build_hash' => 'ZbMpHNx',
    'container.build_id' => '9190d780',
    'container.build_time' => 1541657568,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZbMpHNx');
