<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mQbJNd_' shared service.

return $this->privates['.service_locator.mQbJNd_'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('projeto' => function (): \App\Entity\HoraLancada {
    return ($this->privates['.errored..service_locator.mQbJNd_.App\Entity\HoraLancada'] ?? $this->load('getHoraLancada2Service.php'));
}));
