<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._8lUFnT' shared service.

return $this->privates['.service_locator._8lUFnT'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('funcionario' => function (): \App\Entity\Funcionario {
    return ($this->privates['.errored..service_locator._8lUFnT.App\Entity\Funcionario'] ?? $this->load('getFuncionarioService.php'));
}));
