<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RhYDhKl' shared service.

return $this->privates['.service_locator.RhYDhKl'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('projeto' => function (): \App\Entity\Projeto {
    return ($this->privates['.errored..service_locator.RhYDhKl.App\Entity\Projeto'] ?? $this->load('getProjetoService.php'));
}));
