<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\FuncionarioController::edita' => function () {
    return ($this->privates['.service_locator._8lUFnT'] ?? $this->load('get_ServiceLocator_8lUFnTService.php'));
}, 'App\\Controller\\FuncionarioController::mostra' => function () {
    return ($this->privates['.service_locator._8lUFnT'] ?? $this->load('get_ServiceLocator_8lUFnTService.php'));
}, 'App\\Controller\\FuncionarioController::mostraAction' => function () {
    return ($this->privates['.service_locator._8lUFnT'] ?? $this->load('get_ServiceLocator_8lUFnTService.php'));
}, 'App\\Controller\\FuncionarioController::remove' => function () {
    return ($this->privates['.service_locator._8lUFnT'] ?? $this->load('get_ServiceLocator_8lUFnTService.php'));
}, 'App\\Controller\\HoraLancadaController::delete' => function () {
    return ($this->privates['.service_locator.mQbJNd_'] ?? $this->load('get_ServiceLocator_MQbJNdService.php'));
}, 'App\\Controller\\HoraLancadaController::edita' => function () {
    return ($this->privates['.service_locator.jCwLjvV'] ?? $this->load('get_ServiceLocator_JCwLjvVService.php'));
}, 'App\\Controller\\HoraLancadaController::mostra' => function () {
    return ($this->privates['.service_locator.jCwLjvV'] ?? $this->load('get_ServiceLocator_JCwLjvVService.php'));
}, 'App\\Controller\\ProjetoController::delete' => function () {
    return ($this->privates['.service_locator.RhYDhKl'] ?? $this->load('get_ServiceLocator_RhYDhKlService.php'));
}, 'App\\Controller\\ProjetoController::edita' => function () {
    return ($this->privates['.service_locator.RhYDhKl'] ?? $this->load('get_ServiceLocator_RhYDhKlService.php'));
}, 'App\\Controller\\ProjetoController::mostra' => function () {
    return ($this->privates['.service_locator.RhYDhKl'] ?? $this->load('get_ServiceLocator_RhYDhKlService.php'));
}, 'App\\Controller\\UsuarioController::delete' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\UsuarioController::edita' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\UsuarioController::mostra' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\FuncionarioController:edita' => function () {
    return ($this->privates['.service_locator._8lUFnT'] ?? $this->load('get_ServiceLocator_8lUFnTService.php'));
}, 'App\\Controller\\FuncionarioController:mostra' => function () {
    return ($this->privates['.service_locator._8lUFnT'] ?? $this->load('get_ServiceLocator_8lUFnTService.php'));
}, 'App\\Controller\\FuncionarioController:mostraAction' => function () {
    return ($this->privates['.service_locator._8lUFnT'] ?? $this->load('get_ServiceLocator_8lUFnTService.php'));
}, 'App\\Controller\\FuncionarioController:remove' => function () {
    return ($this->privates['.service_locator._8lUFnT'] ?? $this->load('get_ServiceLocator_8lUFnTService.php'));
}, 'App\\Controller\\HoraLancadaController:delete' => function () {
    return ($this->privates['.service_locator.mQbJNd_'] ?? $this->load('get_ServiceLocator_MQbJNdService.php'));
}, 'App\\Controller\\HoraLancadaController:edita' => function () {
    return ($this->privates['.service_locator.jCwLjvV'] ?? $this->load('get_ServiceLocator_JCwLjvVService.php'));
}, 'App\\Controller\\HoraLancadaController:mostra' => function () {
    return ($this->privates['.service_locator.jCwLjvV'] ?? $this->load('get_ServiceLocator_JCwLjvVService.php'));
}, 'App\\Controller\\ProjetoController:delete' => function () {
    return ($this->privates['.service_locator.RhYDhKl'] ?? $this->load('get_ServiceLocator_RhYDhKlService.php'));
}, 'App\\Controller\\ProjetoController:edita' => function () {
    return ($this->privates['.service_locator.RhYDhKl'] ?? $this->load('get_ServiceLocator_RhYDhKlService.php'));
}, 'App\\Controller\\ProjetoController:mostra' => function () {
    return ($this->privates['.service_locator.RhYDhKl'] ?? $this->load('get_ServiceLocator_RhYDhKlService.php'));
}, 'App\\Controller\\UsuarioController:delete' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\UsuarioController:edita' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\UsuarioController:mostra' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
})));
