<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator._8lUFnT.App\Entity\Funcionario' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator._8lUFnT": it references class "App\\Entity\\Funcionario" but no such service exists.');
