<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.mQbJNd_.App\Entity\HoraLancada' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.mQbJNd_": it references class "App\\Entity\\HoraLancada" but no such service exists.');
