<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\LivroController::delete' => function () {
    return ($this->privates['.service_locator.bCHlcTr'] ?? $this->load('get_ServiceLocator_BCHlcTrService.php'));
}, 'App\\Controller\\LivroController::edita' => function () {
    return ($this->privates['.service_locator.bCHlcTr'] ?? $this->load('get_ServiceLocator_BCHlcTrService.php'));
}, 'App\\Controller\\LivroController::mostra' => function () {
    return ($this->privates['.service_locator.bCHlcTr'] ?? $this->load('get_ServiceLocator_BCHlcTrService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\UsuarioController::delete' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\UsuarioController::edita' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\UsuarioController::mostra' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\LivroController:delete' => function () {
    return ($this->privates['.service_locator.bCHlcTr'] ?? $this->load('get_ServiceLocator_BCHlcTrService.php'));
}, 'App\\Controller\\LivroController:edita' => function () {
    return ($this->privates['.service_locator.bCHlcTr'] ?? $this->load('get_ServiceLocator_BCHlcTrService.php'));
}, 'App\\Controller\\LivroController:mostra' => function () {
    return ($this->privates['.service_locator.bCHlcTr'] ?? $this->load('get_ServiceLocator_BCHlcTrService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\UsuarioController:delete' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\UsuarioController:edita' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}, 'App\\Controller\\UsuarioController:mostra' => function () {
    return ($this->privates['.service_locator.PaAmpFZ'] ?? $this->load('get_ServiceLocator_PaAmpFZService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
