<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.bCHlcTr.App\Entity\Livro' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.bCHlcTr": it references class "App\\Entity\\Livro" but no such service exists.');
