<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHnDnFnw\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHnDnFnw/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHnDnFnw.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHnDnFnw\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerHnDnFnw\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'HnDnFnw',
    'container.build_id' => 'b7406440',
    'container.build_time' => 1541719052,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHnDnFnw');
